controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

google_calendar:
    path: /google-calendar
    controller: App\Controller\GoogleCalendarController::index


api_download_reservations:
    path: '/download/reservations'
    controller: App\Controller\ApiDownloadController::downloadReservations

api_download_reservations_js:
    path: /download/reservationsjs
    controller: App\Controller\ApiDownloadController::downloadReservationsJs


api_download_habitats:
    path: '/download/habitats'
    controller: App\Controller\ApiDownloadController::downloadHabitats

api_download_habitats_pdf:
    path: '/download/habitatspdf'
    controller: App\Controller\ApiDownloadController::downloadHabitatsPdf
